<?php
namespace EfikaTest\EventManager;

use Efika\EventManager\EventHandlerCallback;

/**
 * Generated by PHPUnit_SkeletonGenerator.
 */
class EventHandlerCallbackTest extends \PHPUnit_Framework_TestCase
{

    public function testCallbackInitiation()
    {
        $callback = new EventHandlerCallback(
            function($augend,$addend)
            {
                return $augend + $addend;
            }
        );

        $this->assertInstanceOf(
            'Efika\EventManager\EventHandlerCallback',
            $callback
        );
        $this->assertTrue($callback->hasCallback());

        return $callback;
    }

    public function testCallbackIsCallable()
    {
        $callback = $this->testCallbackInitiation();
        $this->assertTrue($callback->isCallable());
    }

    public function testCallbackExecution()
    {

        $callback = $this->testCallbackInitiation();
        $this->assertEquals(25+23,$callback->execute([25,23]));
    }

}
