<?php
namespace EfikaTest\Di;

use Efika\Di\DiContainer;
use EfikaTest\Di\TestLibrary\CustomExpandable;

/**
 * Generated by PHPUnit_SkeletonGenerator.
 */
class DiContainerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \Efika\Di\DiContainer|null
     */
    private $di = null;

    public function __construct(){
        $this->di = DiContainer::getInstance();
    }


    public function testServiceLiveCycle(){
        $di = $this->di;

        //create a custom object
        $service = $di->createService(new CustomExpandable(), 'first');
        $this->assertInstanceOf('Efika\Di\DiService', $service);

        //create a custom object
        $service = $di->createService($service, 'second');
        $this->assertInstanceOf('Efika\Di\DiService', $service);

        //get class as service
        $service = $di->getClassAsService('EfikaTest\Di\TestLibrary\CustomExpandable');
        $this->assertInstanceOf('Efika\Di\DiService', $service);

        //get class
        $service = $di->getService('first');
        $this->assertInstanceOf('Efika\Di\DiService', $service);

        //get class
        $service = $di->getService('second');
        $this->assertInstanceOf('Efika\Di\DiService', $service);

        //get class
        $service = $di->getService('EfikaTest\Di\TestLibrary\CustomExpandable');
        $this->assertInstanceOf('Efika\Di\DiService', $service);
    }

    public function testClassnameAssosiation(){
        $di = $this->di;
        $service = $di->getClassAsService('EfikaTest\Di\TestLibrary\CustomExpandable', new \stdClass());
        $this->assertInstanceOf('Efika\Di\DiService', $service);
    }

}
