<?php
namespace EfikaTest\EventManager;


use Efika\EventManager\StaticEventManager;
use ReflectionClass;

/**
 * Generated by PHPUnit_SkeletonGenerator.
 */
class StaticEventManagerTest extends EventManagerTest
{

    /**
     *
     */
    public function testUsesSingletonTrait()
    {
        $sem = StaticEventManager::getInstance();
        $this->assertTrue(trait_exists('Efika\Common\SingletonTrait', false));
        $reflection = new ReflectionClass($sem);
        $this->assertContains('Efika\Common\SingletonTrait', $reflection->getTraitNames());
        $this->assertTrue($reflection->getMethods() > 0);

    }
}
