<?php
namespace EfikaTest\Di;

use Efika\Di\DiService;
use EfikaTest\Di\TestLibrary\CustomExpandable;

/**
 * Generated by PHPUnit_SkeletonGenerator.
 */
class DiExpandableTest extends \PHPUnit_Framework_TestCase
{

}
