<?php
namespace EfikaTest\Di;


use Efika\Di\DiException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-29 at 15:42:32.
 */
class DiExceptionTest extends \PHPUnit_Framework_TestCase
{

    public function testThrowException(){

        try {
            throw new DiException('Test Error');
        } catch (Exception $e){
            $this->assertInstanceOf('\Exception',$e);
            $this->assertInstanceOf('Efika\EventManager\DiException',$e);
        }
    }
}
